version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres

  worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    env_file: .env
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13-alpine
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: 